branches:
    only:
        - master

cache:
    directories:
        - $HOME/cache
    
sudo: required

services:
    - docker

before_install:
    - docker build -t webapp:test -f ./Lab6/docker/Dockerfile .

script:
    - docker run -it --rm -v $HOME/cache/.nuget/packages webapp:test
